# 开发时可以写到本地，上线后搬到配置中心
spring:
  cloud:
    gateway:
      routes:
        - id: baidu_test
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_test
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
server:
  port: 88

